jwt:
  secret: ${jwt.secret}

spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: classpath:values.yml

internal:
  token: ${internal.token}
