jwt:
  secret: 8xK2vN9pQmL4wR7sT1uY3aB5cD6eF8gH0iJ2kL4mN6oP8qR0sT2uV4wX6yZ8

database:
  url: jdbc:postgresql://localhost:5432/Test
  username: postgres
  password: 1205200Ft

internal:
  token: a1b2c3d4-e5f6-7890-abcd-ef1234567890
